[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[unix_http_server]
file=/tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:xvnc]
command=/usr/bin/Xtigervnc :1 -geometry %(ENV_RESOLUTION)s -depth 24 -SecurityTypes None -localhost -rfbport 5901 -AlwaysShared -AcceptSetDesktopSize
priority=10
autorestart=true

[program:desktop]
command=/usr/bin/dbus-launch --exit-with-session /usr/bin/startxfce4
environment=DISPLAY=":1",HOME="%(ENV_HOME)s",USER="%(ENV_USER)s"
priority=20
startsecs=3
autorestart=true

[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc 6080 localhost:5901
priority=30
autorestart=true
